name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  codeowners:
    name: Codeowners Lint
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: git config --get remote.origin.url
    - name: Run Linter
      uses: fmenezes/codeowners-action@v5
      with:
        dir: '.'
        token: ${{ secrets.TOKEN }}
      